### ISSUE TITLE
Broken on newer kernels

### ISSUE THREAD

**Issue by rajb245** [Zibri/afulnx#1]
I get an error: ./arch/x86/include/asm/uaccess.h:32:9: error: dereferencing pointer to incomplete type ‘struct task_struct’

Googling indicates that this is due to updates in the kernel:
https://lkml.org/lkml/2017/9/30/189

I grabbed the files out of the .temp folder while running AFULNX when it does the compile step, then modified the code to #include <linux/uaccess.h> as suggested on the kernel mailing list . However, I can't quite figure out how to pack that back into the AFULNX binary. Can you provide some tips on how to patch this back into the file?

**Comment by Zibri** [comment]
If you check, there is already #include <linux/uaccess.h> in amiwrap.h

Did you remove the reference to asm/uaccess.h ?

**Comment by Zibri** [comment]
Please try afulnx-5.05.04Z2.tar.gz  (in the release page)
It should be fixed.

**Comment by rajb245** [comment]
I won't be testing the fix as I've moved on and do not have a need for updating the BIOS on that machine any longer. If I revisit and test, I'll comment here. Consider the issue closed.
